# Generated by Django 2.1.5 on 2019-02-25 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(default=' ', max_length=12, validators=[django.core.validators.RegexValidator('^(\\d{10})$', code='invalid_phone', message='Please enter a phone number of the format XXXXXXXXXX')]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'Please enter a Name'}, max_length=100),
        ),
    ]
